### ISSUE TITLE
encode_ogg appears to fail because there's no "occenc_path" which seems like a type I don't see in the code 

### ISSUE THREAD

**Issue by jgbell** [fluffy-critter/bandcrash#45]
On Ubuntu Linux Intel/64, I today installed bandcrash via pipx. I also have installed, and verified that I have vorbis-tools. However when running bandcrash, it fails to create anything in the ogg subdirectory of the out directory. I notice the following error, which mentions "occenc_path" that definitely seems like a typo for "oggenc_path". 

> bandcrash/__init__.py", line 175, in encode_ogg
>     run_encoder(out_path, [options.occenc_path, *encode_args.split(),
>                            ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Namespace' object has no attribute 'occenc_path'

When I look at the code here on GitHub I see this line is "oggenc_path" however, if I 

> grep occenc /home/me/.local/pipx/.cache/87c926260f4033d/lib/python3.11/site-packages/bandcrash/__init__.py 

I find

>  run_encoder(out_path, [options.occenc_path, *encode_args.split(),

So, my guess is this was an error that got fixed, but for some reason I've got the old code? Not sure how to fix this on my side, except manually editing it, maybe … BRB

Yes, if I manually edit that, it now works. I find the ogg subdirectory filled. So, I guess I'm just saying that there appears to be old code out there that is being installed by pipx as of today. I guess …  FYI?

**Comment by fluffy-critter** [comment]
Yeah, that's a known issue that snuck in for the most recent release, and I meant to publish a fix for it to pypi but it slipped my mind. Sorry about that! I'll take care of that right now.

**Comment by jgbell** [comment]
Closed.

**Comment by fluffy-critter** [comment]
Just published v0.3.4 to pypi. Sorry again, I've been deep in working on the GUI. :)
